version: "3.9"
services:
  web:
    build: .
    container_name: django-api
    command: python manage.py runserver 0.0.0.0:8800
    volumes:
      - .:/app
    ports:
      - "8800:8800"
    env_file:
      - .env
    depends_on: []